# Generated by Django 3.2 on 2023-02-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'verbose_name_plural': 'Жанры фильма'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Актёра', 'verbose_name_plural': 'Актёры'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name_plural': 'Актёры фильма'},
        ),
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='movies/', verbose_name='file'),
        ),
    ]
